### PR TITLE
64bit

### PR DESCRIPTION
**Pull request by stvv0000**
hi, dev! can you please make 64 bit version?

### CODE REVIEW

**Comment by HarGabt** [comment]
Can you share the build, please? Thanks in advance.

**Comment by Mateos81** [comment]
> Can you share the build, please? Thanks in advance.

There: https://github.com/s0hv/foo_discord_rich/releases

**Comment by HarGabt** [comment]
> There: https://github.com/s0hv/foo_discord_rich/releases

beta 6 does not install on 64-bit version of foobar2000
`Could not load component "foo_discord_rich-2.fb2k-component": This component was built for a different processor architecture.
`

**Comment by Mateos81** [comment]
> > There: https://github.com/s0hv/foo_discord_rich/releases
> 
> beta 6 does not install on 64-bit version of foobar2000 `Could not load component "foo_discord_rich-2.fb2k-component": This component was built for a different processor architecture. `

Yeah, since there were commits here from that fork I thought it would work but nope

I'm retrieving the repo to check if there's a x64 build possible

**Comment by s0hv** [comment]
I made a pre-release 64bit build for those who really need it. 
https://github.com/s0hv/foo_discord_rich/releases/tag/64-bit-prerelase

**Comment by stvv0000** [comment]
image
Thanks!

**Comment by TheQwertiest** [comment]
Thanks for the PR, but this does not seem like something I can merge, since it contains many other changes.
FWIW, x64 support was added to nightly build.

**Pull request closed without merging**
